# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: relay.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brelay.proto\x12\x05relay\"\x17\n\x07Message\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t2=\n\x0cRelayService\x12-\n\tRelayData\x12\x0e.relay.Message\x1a\x0e.relay.Message\"\x00\x42)Z\'C:/Users/dlemi/Documents/GO/relay;relayb\x06proto3')



_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'relay_pb2'
  # @@protoc_insertion_point(class_scope:relay.Message)
  })
_sym_db.RegisterMessage(Message)

_RELAYSERVICE = DESCRIPTOR.services_by_name['RelayService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\'C:/Users/dlemi/Documents/GO/relay;relay'
  _MESSAGE._serialized_start=22
  _MESSAGE._serialized_end=45
  _RELAYSERVICE._serialized_start=47
  _RELAYSERVICE._serialized_end=108
# @@protoc_insertion_point(module_scope)
